"use client";
import React, { useRef, useState, useEffect } from 'react';
import api, { setAccessToken } from '../../../../lib/api';
import styles from './verify.module.css';

export default function Verify2faPage() {
  const [tempToken, setTempToken] = useState<string | null>(null);
  const [errorMsg, setErrorMsg] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isBackupMode, setIsBackupMode] = useState(false);

  // 6-digit OTP fields
  const [otp, setOtp] = useState<string[]>(Array(6).fill(''));
  const inputRefs = useRef<HTMLInputElement[]>([]);

  // Backup code field (10-char alphanumeric string)
  const [backupCode, setBackupCode] = useState('');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const token = sessionStorage.getItem('temp2faToken');
      if (!token) {
        window.location.href = '/login';
      } else {
        setTempToken(token);
      }
    }
  }, []);

  // Handle standard OTP inputs change
  const handleChange = (index: number, value: string) => {
    const cleanValue = value.replace(/[^0-9]/g, '');
    if (!cleanValue) return;

    const newOtp = [...otp];
    // Take only the last digit typed
    newOtp[index] = cleanValue[cleanValue.length - 1];
    setOtp(newOtp);

    // Auto focus next input
    if (index < 5 && cleanValue.length > 0) {
      inputRefs.current[index + 1]?.focus();
    }
  };

  // Handle key press to navigate or submit
  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Backspace') {
      if (!otp[index] && index > 0) {
        const newOtp = [...otp];
        newOtp[index - 1] = '';
        setOtp(newOtp);
        inputRefs.current[index - 1]?.focus();
      } else {
        const newOtp = [...otp];
        newOtp[index] = '';
        setOtp(newOtp);
      }
    } else if (e.key === 'Enter') {
      e.preventDefault();
      handleSubmit(e);
    }
  };

  // Handle pasting of full 6-digit code
  const handlePaste = (e: React.ClipboardEvent<HTMLInputElement>) => {
    e.preventDefault();
    const pastedData = e.clipboardData.getData('text').trim();
    if (/^\d{6}$/.test(pastedData)) {
      const digits = pastedData.split('');
      setOtp(digits);
      // Focus the last input box
      inputRefs.current[5]?.focus();
    }
  };

  // Submit standard OTP or backup code to backend
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!tempToken) return;

    setErrorMsg('');
    setIsLoading(true);

    const code = isBackupMode ? backupCode.trim() : otp.join('');
    if (!code || code.length < 6) {
      setErrorMsg(isBackupMode ? 'Please enter a valid backup code.' : 'Please enter a 6-digit code.');
      setIsLoading(false);
      return;
    }

    try {
      const res = await api.post(
        '/auth/verify-2fa',
        { code },
        { headers: { Authorization: `Bearer ${tempToken}` } }
      );

      const { accessToken } = res.data;
      setAccessToken(accessToken);
      
      // Invalidate the temp session from sessionStorage
      sessionStorage.removeItem('temp2faToken');
      
      window.location.href = '/dashboard';
    } catch (err: any) {
      setIsLoading(false);
      const responseData = err.response?.data;
      
      if (responseData?.message) {
        setErrorMsg(responseData.message);
      } else {
        setErrorMsg('Verification failed. Please check the code and try again.');
      }
    }
  };

  // Reset fields when changing verification modes
  const toggleMode = () => {
    setErrorMsg('');
    setIsBackupMode(!isBackupMode);
    setOtp(Array(6).fill(''));
    setBackupCode('');
  };

  return (
    <div className={styles.glassContainer}>
      <div className={styles.header}>
        <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '1.25rem' }}>
          <svg fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24" style={{ width: '48px', height: '48px', color: 'var(--primary)' }}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.57-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
          </svg>
        </div>
        <h1 className={styles.title}>Two-Factor Verification</h1>
        <p className={styles.subtitle}>
          {isBackupMode
            ? 'Enter one of your 10-character backup recovery codes.'
            : 'Enter the 6-digit security code generated by your authenticator app.'}
        </p>
      </div>

      {errorMsg && <div className={styles.errorMessage}>{errorMsg}</div>}

      {!isBackupMode && (
        <div className={styles.instructions}>
          <h4>Standard Authenticators Supported:</h4>
          <p>Open Google Authenticator, Microsoft Authenticator, Authy, or similar and type the code displayed for AttendanceTracker.</p>
        </div>
      )}

      <form onSubmit={handleSubmit} className={styles.form}>
        {isBackupMode ? (
          <div className={styles.inputGroup}>
            <input
              type="text"
              className={styles.input}
              maxLength={10}
              placeholder="e.g. ab12cd34ef"
              value={backupCode}
              onChange={(e) => setBackupCode(e.target.value.toLowerCase().replace(/[^a-z0-9]/g, ''))}
              required
              disabled={isLoading}
              autoFocus
            />
          </div>
        ) : (
          <div className={styles.otpGrid}>
            {otp.map((digit, idx) => (
              <input
                key={idx}
                ref={(el) => {
                  if (el) inputRefs.current[idx] = el;
                }}
                type="text"
                pattern="[0-9]*"
                inputMode="numeric"
                maxLength={2}
                className={styles.otpInput}
                value={digit}
                onChange={(e) => handleChange(idx, e.target.value)}
                onKeyDown={(e) => handleKeyDown(idx, e)}
                onPaste={handlePaste}
                disabled={isLoading}
                autoFocus={idx === 0}
                required
              />
            ))}
          </div>
        )}

        <button type="submit" className={styles.submitBtn} disabled={isLoading}>
          {isLoading ? <span className={styles.loader}></span> : 'Verify & Continue'}
        </button>
      </form>

      <div className={styles.footerActions}>
        <button type="button" onClick={toggleMode} className={styles.actionLink}>
          {isBackupMode ? 'Use Authenticator Code instead' : 'Lost authenticator? Use a backup recovery code'}
        </button>
        <a href="/login" className={styles.backToLogin}>
          <svg className={styles.arrowIcon} fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back to sign in
        </a>
      </div>
    </div>
  );
}
